"""
Qutlas Data Schema

Defines the canonical data structures used across the entire platform.
Every sensor reading, production run, control action, and material
outcome is represented using these types.

These are the interfaces between all layers of the system.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional
import uuid


# ── Enums ──────────────────────────────────────────────────────────────────

class FiberClass(str, Enum):
    """Engineered basalt fiber classes the platform can produce."""
    STRUCTURAL         = "structural"
    HIGH_TEMPERATURE   = "high_temperature"
    ELECTRICAL         = "electrical_insulation"
    CORROSION_RESISTANT = "corrosion_resistant"
    PRECISION          = "precision_structural"


class RunStatus(str, Enum):
    """Status of a production run."""
    PENDING    = "pending"
    ACTIVE     = "active"
    CONVERGING = "converging"   # system steering toward target
    STABLE     = "stable"       # within tolerance band
    COMPLETE   = "complete"
    ABORTED    = "aborted"
    FAILED     = "failed"


class DataSource(str, Enum):
    """Origin of a sensor reading."""
    HARDWARE  = "hardware"    # real physical sensor
    SIMULATOR = "simulator"   # process simulation
    SYNTHETIC = "synthetic"   # generated for training


# ── Sensor Readings ────────────────────────────────────────────────────────

@dataclass
class SensorReading:
    """
    A single timestamped snapshot of all sensor measurements
    from the production environment.

    All values use SI units unless noted.
    """
    timestamp:           datetime
    source:              DataSource

    # Layer 01 — Furnace sensors
    furnace_temp_c:      float               # °C — pyrometer
    melt_viscosity_cp:   Optional[float]     # cP — inferred from draw tension
    melt_flow_rate:      Optional[float]     # g/min

    # Layer 01 — Fiber draw sensors
    fiber_diameter_um:   float               # µm — laser micrometer
    draw_speed_ms:       float               # m/s
    draw_tension_n:      Optional[float]     # N — load cell

    # Layer 01 — Cooling sensors
    cooling_zone_temp_c: Optional[float]     # °C — post-draw cooling section
    airflow_rate_lpm:    Optional[float]     # L/min

    # Layer 01 — Optical emission (spectral, simplified to key bands)
    optical_emission:    Optional[list[float]] = None  # relative intensity array

    # Metadata
    run_id:              Optional[str] = None
    sequence:            int = 0             # timestep index within run

    def is_complete(self) -> bool:
        """Returns True if all critical sensor values are present."""
        return all([
            self.furnace_temp_c is not None,
            self.fiber_diameter_um is not None,
            self.draw_speed_ms is not None,
        ])


# ── Control Actions ────────────────────────────────────────────────────────

@dataclass
class ControlAction:
    """
    A set of parameter adjustments to be sent to the manufacturing
    equipment. Generated by the adaptive control layer.
    """
    timestamp:              datetime
    run_id:                 str

    # Furnace control
    furnace_temp_setpoint_c:  float          # °C target
    furnace_ramp_rate_c_min:  float = 5.0    # °C/min max ramp rate

    # Draw control
    draw_speed_setpoint_ms:   float = 12.0   # m/s target
    draw_tension_setpoint_n:  Optional[float] = None

    # Cooling control
    cooling_airflow_setpoint: float = 50.0   # L/min target

    # Safety
    emergency_stop:           bool = False
    reason:                   Optional[str] = None


# ── Property Predictions ───────────────────────────────────────────────────

@dataclass
class PropertyPrediction:
    """
    Predicted material properties generated by the Materials Engine
    (Layer 03) from current sensor readings.
    """
    timestamp:              datetime
    run_id:                 str
    model_version:          str

    # Mechanical properties
    tensile_strength_gpa:   float            # GPa
    elastic_modulus_gpa:    float            # GPa
    elongation_pct:         float            # % at break

    # Thermal properties
    thermal_stability_c:    float            # max service temperature °C

    # Electrical properties
    dielectric_strength:    Optional[float]  # kV/mm

    # Quality
    diameter_cv_pct:        float            # coefficient of variation %
    defect_probability:     float            # 0–1

    # Confidence
    prediction_confidence:  float            # 0–1
    within_tolerance:       bool = False


# ── Production Recipes ─────────────────────────────────────────────────────

@dataclass
class FiberRecipe:
    """
    A named fiber production target. Specifies the desired material
    properties and the tolerance bands around each.

    Recipes are loaded from YAML files in control/recipes/.
    """
    name:                   str
    fiber_class:            FiberClass
    description:            str

    # Target properties
    target_tensile_gpa:     float
    target_modulus_gpa:     float
    target_diameter_um:     float
    target_thermal_c:       float

    # Tolerance bands (±)
    tol_tensile_gpa:        float = 0.1
    tol_modulus_gpa:        float = 0.2
    tol_diameter_um:        float = 2.0
    tol_thermal_c:          float = 20.0

    # Initial parameter hints (used to seed the controller)
    initial_temp_c:         float = 1480.0
    initial_draw_speed_ms:  float = 12.0
    initial_airflow_lpm:    float = 50.0

    # Constraints
    max_temp_c:             float = 1580.0
    min_temp_c:             float = 1400.0
    max_draw_speed_ms:      float = 20.0

    def is_met_by(self, prediction: PropertyPrediction) -> bool:
        """Returns True if a property prediction satisfies this recipe's targets."""
        return all([
            abs(prediction.tensile_strength_gpa - self.target_tensile_gpa) <= self.tol_tensile_gpa,
            abs(prediction.elastic_modulus_gpa  - self.target_modulus_gpa) <= self.tol_modulus_gpa,
            abs(prediction.diameter_cv_pct)      <= 3.0,
        ])


# ── Production Runs ────────────────────────────────────────────────────────

@dataclass
class ProductionRun:
    """
    A complete record of a production run from start to completion.
    This is the primary unit of data exported for model training.
    """
    run_id:         str = field(default_factory=lambda: str(uuid.uuid4()))
    recipe:         Optional[FiberRecipe] = None
    status:         RunStatus = RunStatus.PENDING
    source:         DataSource = DataSource.SIMULATOR

    started_at:     Optional[datetime] = None
    completed_at:   Optional[datetime] = None

    # Time-series data accumulated during the run
    readings:       list[SensorReading]  = field(default_factory=list)
    actions:        list[ControlAction]  = field(default_factory=list)
    predictions:    list[PropertyPrediction] = field(default_factory=list)

    # Final material test results (filled after physical testing)
    outcome_tensile_gpa:    Optional[float] = None
    outcome_modulus_gpa:    Optional[float] = None
    outcome_diameter_cv:    Optional[float] = None
    outcome_thermal_c:      Optional[float] = None

    # Notes
    notes:          str = ""

    @property
    def duration_seconds(self) -> Optional[float]:
        if self.started_at and self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None

    @property
    def timestep_count(self) -> int:
        return len(self.readings)
